/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */

package name.mrkandreev.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class DataResponse extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3935006226818873985L;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"DataResponse\",\"namespace\":\"name.mrkandreev.avro\",\"fields\":[{\"name\":\"requestId\",\"type\":\"string\"},{\"name\":\"isSuccess\",\"type\":\"boolean\"},{\"name\":\"errorMessage\",\"type\":\"string\"},{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"DataResponseValue\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"value\",\"type\":\"double\"}]},\"java-class\":\"java.util.List\"}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DataResponse> ENCODER =
      new BinaryMessageEncoder<DataResponse>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DataResponse> DECODER =
      new BinaryMessageDecoder<DataResponse>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DataResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DataResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DataResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DataResponse>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DataResponse to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DataResponse from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DataResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
   *                             this class
   */
  public static DataResponse fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence requestId;
  private boolean isSuccess;
  private java.lang.CharSequence errorMessage;
  private java.util.List<name.mrkandreev.avro.DataResponseValue> values;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the
   * schema. If that is desired then one should use <code>newBuilder()</code>.
   */
  public DataResponse() {
  }

  /**
   * All-args constructor.
   *
   * @param requestId    The new value for requestId
   * @param isSuccess    The new value for isSuccess
   * @param errorMessage The new value for errorMessage
   * @param values       The new value for values
   */
  public DataResponse(
      java.lang.CharSequence requestId,
      java.lang.Boolean isSuccess,
      java.lang.CharSequence errorMessage,
      java.util.List<name.mrkandreev.avro.DataResponseValue> values) {
    this.requestId = requestId;
    this.isSuccess = isSuccess;
    this.errorMessage = errorMessage;
    this.values = values;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return requestId;
      case 1:
        return isSuccess;
      case 2:
        return errorMessage;
      case 3:
        return values;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        requestId = (java.lang.CharSequence) value$;
        break;
      case 1:
        isSuccess = (java.lang.Boolean) value$;
        break;
      case 2:
        errorMessage = (java.lang.CharSequence) value$;
        break;
      case 3:
        values = (java.util.List<name.mrkandreev.avro.DataResponseValue>) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'requestId' field.
   *
   * @return The value of the 'requestId' field.
   */
  public java.lang.CharSequence getRequestId() {
    return requestId;
  }

  /**
   * Sets the value of the 'requestId' field.
   *
   * @param value the value to set.
   */
  public void setRequestId(java.lang.CharSequence value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'isSuccess' field.
   *
   * @return The value of the 'isSuccess' field.
   */
  public boolean getIsSuccess() {
    return isSuccess;
  }

  /**
   * Sets the value of the 'isSuccess' field.
   *
   * @param value the value to set.
   */
  public void setIsSuccess(boolean value) {
    this.isSuccess = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   *
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.CharSequence getErrorMessage() {
    return errorMessage;
  }

  /**
   * Sets the value of the 'errorMessage' field.
   *
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.CharSequence value) {
    this.errorMessage = value;
  }

  /**
   * Gets the value of the 'values' field.
   *
   * @return The value of the 'values' field.
   */
  public java.util.List<name.mrkandreev.avro.DataResponseValue> getValues() {
    return values;
  }

  /**
   * Sets the value of the 'values' field.
   *
   * @param value the value to set.
   */
  public void setValues(java.util.List<name.mrkandreev.avro.DataResponseValue> value) {
    this.values = value;
  }

  /**
   * Creates a new DataResponse RecordBuilder.
   *
   * @return A new DataResponse RecordBuilder
   */
  public static name.mrkandreev.avro.DataResponse.Builder newBuilder() {
    return new name.mrkandreev.avro.DataResponse.Builder();
  }

  /**
   * Creates a new DataResponse RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new DataResponse RecordBuilder
   */
  public static name.mrkandreev.avro.DataResponse.Builder newBuilder(
      name.mrkandreev.avro.DataResponse.Builder other) {
    if (other == null) {
      return new name.mrkandreev.avro.DataResponse.Builder();
    } else {
      return new name.mrkandreev.avro.DataResponse.Builder(other);
    }
  }

  /**
   * Creates a new DataResponse RecordBuilder by copying an existing DataResponse instance.
   *
   * @param other The existing instance to copy.
   * @return A new DataResponse RecordBuilder
   */
  public static name.mrkandreev.avro.DataResponse.Builder newBuilder(
      name.mrkandreev.avro.DataResponse other) {
    if (other == null) {
      return new name.mrkandreev.avro.DataResponse.Builder();
    } else {
      return new name.mrkandreev.avro.DataResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for DataResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder
      extends org.apache.avro.specific.SpecificRecordBuilderBase<DataResponse>
      implements org.apache.avro.data.RecordBuilder<DataResponse> {

    private java.lang.CharSequence requestId;
    private boolean isSuccess;
    private java.lang.CharSequence errorMessage;
    private java.util.List<name.mrkandreev.avro.DataResponseValue> values;

    /**
     * Creates a new Builder
     */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(name.mrkandreev.avro.DataResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.isSuccess)) {
        this.isSuccess = data().deepCopy(fields()[1].schema(), other.isSuccess);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[2].schema(), other.errorMessage);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.values)) {
        this.values = data().deepCopy(fields()[3].schema(), other.values);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing DataResponse instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(name.mrkandreev.avro.DataResponse other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.isSuccess)) {
        this.isSuccess = data().deepCopy(fields()[1].schema(), other.isSuccess);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[2].schema(), other.errorMessage);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.values)) {
        this.values = data().deepCopy(fields()[3].schema(), other.values);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Gets the value of the 'requestId' field.
     *
     * @return The value.
     */
    public java.lang.CharSequence getRequestId() {
      return requestId;
    }

    /**
     * Sets the value of the 'requestId' field.
     *
     * @param value The value of 'requestId'.
     * @return This builder.
     */
    public name.mrkandreev.avro.DataResponse.Builder setRequestId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.requestId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'requestId' field has been set.
     *
     * @return True if the 'requestId' field has been set, false otherwise.
     */
    public boolean hasRequestId() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'requestId' field.
     *
     * @return This builder.
     */
    public name.mrkandreev.avro.DataResponse.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'isSuccess' field.
     *
     * @return The value.
     */
    public boolean getIsSuccess() {
      return isSuccess;
    }

    /**
     * Sets the value of the 'isSuccess' field.
     *
     * @param value The value of 'isSuccess'.
     * @return This builder.
     */
    public name.mrkandreev.avro.DataResponse.Builder setIsSuccess(boolean value) {
      validate(fields()[1], value);
      this.isSuccess = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'isSuccess' field has been set.
     *
     * @return True if the 'isSuccess' field has been set, false otherwise.
     */
    public boolean hasIsSuccess() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'isSuccess' field.
     *
     * @return This builder.
     */
    public name.mrkandreev.avro.DataResponse.Builder clearIsSuccess() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'errorMessage' field.
     *
     * @return The value.
     */
    public java.lang.CharSequence getErrorMessage() {
      return errorMessage;
    }

    /**
     * Sets the value of the 'errorMessage' field.
     *
     * @param value The value of 'errorMessage'.
     * @return This builder.
     */
    public name.mrkandreev.avro.DataResponse.Builder setErrorMessage(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.errorMessage = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'errorMessage' field has been set.
     *
     * @return True if the 'errorMessage' field has been set, false otherwise.
     */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[2];
    }

    /**
     * Clears the value of the 'errorMessage' field.
     *
     * @return This builder.
     */
    public name.mrkandreev.avro.DataResponse.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'values' field.
     *
     * @return The value.
     */
    public java.util.List<name.mrkandreev.avro.DataResponseValue> getValues() {
      return values;
    }

    /**
     * Sets the value of the 'values' field.
     *
     * @param value The value of 'values'.
     * @return This builder.
     */
    public name.mrkandreev.avro.DataResponse.Builder setValues(
        java.util.List<name.mrkandreev.avro.DataResponseValue> value) {
      validate(fields()[3], value);
      this.values = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'values' field has been set.
     *
     * @return True if the 'values' field has been set, false otherwise.
     */
    public boolean hasValues() {
      return fieldSetFlags()[3];
    }

    /**
     * Clears the value of the 'values' field.
     *
     * @return This builder.
     */
    public name.mrkandreev.avro.DataResponse.Builder clearValues() {
      values = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DataResponse build() {
      try {
        DataResponse record = new DataResponse();
        record.requestId =
            fieldSetFlags()[0]
                ? this.requestId
                : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.isSuccess =
            fieldSetFlags()[1] ? this.isSuccess : (java.lang.Boolean) defaultValue(fields()[1]);
        record.errorMessage =
            fieldSetFlags()[2]
                ? this.errorMessage
                : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.values =
            fieldSetFlags()[3]
                ? this.values
                : (java.util.List<name.mrkandreev.avro.DataResponseValue>)
                defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DataResponse> WRITER$ =
      (org.apache.avro.io.DatumWriter<DataResponse>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DataResponse> READER$ =
      (org.apache.avro.io.DatumReader<DataResponse>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
    out.writeString(this.requestId);

    out.writeBoolean(this.isSuccess);

    out.writeString(this.errorMessage);

    long size0 = this.values.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (name.mrkandreev.avro.DataResponseValue e0 : this.values) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0) {
      throw new java.util.ConcurrentModificationException(
          "Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }
  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.requestId = in.readString(this.requestId instanceof Utf8 ? (Utf8) this.requestId : null);

      this.isSuccess = in.readBoolean();

      this.errorMessage =
          in.readString(this.errorMessage instanceof Utf8 ? (Utf8) this.errorMessage : null);

      long size0 = in.readArrayStart();
      java.util.List<name.mrkandreev.avro.DataResponseValue> a0 = this.values;
      if (a0 == null) {
        a0 =
            new SpecificData.Array<name.mrkandreev.avro.DataResponseValue>(
                (int) size0, SCHEMA$.getField("values").schema());
        this.values = a0;
      } else {
        a0.clear();
      }
      SpecificData.Array<name.mrkandreev.avro.DataResponseValue> ga0 =
          (a0 instanceof SpecificData.Array
              ? (SpecificData.Array<name.mrkandreev.avro.DataResponseValue>) a0
              : null);
      for (; 0 < size0; size0 = in.arrayNext()) {
        for (; size0 != 0; size0--) {
          name.mrkandreev.avro.DataResponseValue e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new name.mrkandreev.avro.DataResponseValue();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            this.requestId =
                in.readString(this.requestId instanceof Utf8 ? (Utf8) this.requestId : null);
            break;

          case 1:
            this.isSuccess = in.readBoolean();
            break;

          case 2:
            this.errorMessage =
                in.readString(this.errorMessage instanceof Utf8 ? (Utf8) this.errorMessage : null);
            break;

          case 3:
            long size0 = in.readArrayStart();
            java.util.List<name.mrkandreev.avro.DataResponseValue> a0 = this.values;
            if (a0 == null) {
              a0 =
                  new SpecificData.Array<name.mrkandreev.avro.DataResponseValue>(
                      (int) size0, SCHEMA$.getField("values").schema());
              this.values = a0;
            } else {
              a0.clear();
            }
            SpecificData.Array<name.mrkandreev.avro.DataResponseValue> ga0 =
                (a0 instanceof SpecificData.Array
                    ? (SpecificData.Array<name.mrkandreev.avro.DataResponseValue>) a0
                    : null);
            for (; 0 < size0; size0 = in.arrayNext()) {
              for (; size0 != 0; size0--) {
                name.mrkandreev.avro.DataResponseValue e0 = (ga0 != null ? ga0.peek() : null);
                if (e0 == null) {
                  e0 = new name.mrkandreev.avro.DataResponseValue();
                }
                e0.customDecode(in);
                a0.add(e0);
              }
            }
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
